### ISSUE TITLE
Setting up source

### ISSUE THREAD

**Issue by Microthefirst** [NameNami/OTP-Bot#16]
Running source : $65
Auth system in bot : $100
Auth sys/custom scripts : $130
Auth sys/custom scripts/number spoof : $220
Plivo account : $40
Upgraded twilio : $30
Message me on tele @Microthefirst

**Comment by NameNami** [comment]
damn man but not for now

**Comment by simpleman000** [comment]
bro you make vonage script i hope yes
and give me your tlg

**Comment by NameNami** [comment]
> bro you make vonage script i hope yes
> and give me your tlg

yea sure but i have exam next week and aftdr the exam i kinda free for a week.

**Comment by Microthefirst** [comment]
@simpleman000 do u still need a vonage script?
if so add me on telegram @Microthefirst
