### ISSUE TITLE
I'm not able to run bot.py ,how can I get config txt

### ISSUE THREAD

**Issue by savio778** [NameNami/OTP-Bot#18]
![Screenshot_2022-06-05-09-27-02-90_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/106859021/172034411-5509ad6b-80ef-43d2-acf9-ded1c5b5320f.jpg)

**Comment by NameNami** [comment]
that...i dont really know how to fix that try reinstall discord package

**Comment by yungsucc** [comment]
> 

SEND YO DISCORD ASAP MY BOY; OLD ONE GOT TERMED!

**Comment by NameNami** [comment]
Nami#0527
