### ISSUE TITLE
Credentials are required to create a TwilioClient

### ISSUE THREAD

**Issue by RaZeR6666** [NameNami/OTP-Bot#21]
![image](https://user-images.githubusercontent.com/106828544/175649657-95c155db-5e1a-47c7-82da-ef1c4270debf.png)

Is this maybe cuz i didnt upgrade my twilio account yet

**Comment by NameNami** [comment]
its because u didnt setup the otp bot correctly

**Comment by NameNami** [comment]
or maybe just wait for new otp bot that easier to setup

**Comment by RaZeR6666** [comment]
when will there be a new one?

**Comment by NameNami** [comment]
yea ih
