### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Figgity223** [NameNami/OTP-Bot#24]
Once I open the script it gives this error ====== RESTART: C:\Users\PaveA\Downloads\OTP-Bot-main\OTP-Bot-main\bot.py ======
Traceback (most recent call last):
  File "C:\Users\PaveA\Downloads\OTP-Bot-main\OTP-Bot-main\bot.py", line 1, in <module>
    import discord_slash.utils.manage_commands
ModuleNotFoundError: No module named 'discord_slash'

**Comment by NameNami** [comment]
use compiled version
