### ISSUE TITLE
Selling verified twilio account

### ISSUE THREAD

**Issue by Microthefirst** [NameNami/OTP-Bot#25]
I had a running otp before called memz club otp
I stopped my otp but I still have a twilio account with 50$ credit on it.
Selling for 25$ btc 
Telegram : ActiveKilldare

**Comment by darkhacknet** [comment]
> I had a running otp before called memz club otp I stopped my otp but I still have a twilio account with 50$ credit on it. Selling for 25$ btc Telegram : ActiveKilldare

You are a scammer bro ! ;)
