### ISSUE TITLE
I WANT TO BUY 

### ISSUE THREAD

**Issue by Proffesionalez** [NameNami/OTP-Bot#27]
Yo, am buying the bot / i need help, will pay you my g but your discord is termed send me your discord or add me Jessika#0001

**Comment by daturadev** [comment]
Dude. It's open-source... If you can't work this, you probably should go back to your day job.

**Comment by BluffRunsDat** [comment]
@Proffesionalez if u want to buy a bot i can set one up for u number spoofing loads of modules for cheap
tele : @StackzIsOp

**Comment by horllste** [comment]
Contact me, i will setup the full version for you, check my profile for my contact

**Comment by BluffRunsDat** [comment]
lol im not talking bout a twilio paste source eather. im offering a source with number spoofing that runs on the best api called estate. if u go to that guy u will get a shit otp bot that will bearly take calls

**Comment by BluffRunsDat** [comment]
@horllste ur ass bot has pre recorded scripts 🤣

**Comment by horllste** [comment]
We all just have to be careful.
