### ISSUE TITLE
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by darkhacknet** [NameNami/OTP-Bot#6]
Hello bro ! I have the following issue, would you be so kind to help me  ? 

┌──(xborland㉿kaliLi)-[~/OTP-Bot]
└─$ python3 bot.py                                                                                             13 ⚙
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at /home/xborland/.local/lib/python3.9/site-packages/discord_slash/client.py:416> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "/home/xborland/.local/lib/python3.9/site-packages/discord_slash/client.py", line 440, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id=scope)
  File "/home/xborland/.local/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

I need to mention that my server id and config info its ok ! and the bot permissions seems to be good, the bot is admin of the server also ! 

thanks in advance !

**Comment by NameNami** [comment]
1. Give Enough Permission To The Bot.
2. Make sure the server id correct in the config.txt (not channel id)
3. Make sure the Oauth2 URL Gen is the same as the pic in the link [](https://camo.githubusercontent.com/7ef846842becd81f684fb1f9fcb3daf0267d89b2838b9097c0a7284ac24b68dc/68747470733a2f2f692e696d6775722e636f6d2f35466f7765467a2e6a7067)

**Comment by darkhacknet** [comment]
> 1. Give Enough Permission To The Bot.
> 2. Make sure the server id correct in the config.txt (not channel id)
> 3. Make sure the Oauth2 URL Gen Scopes is the same as the pic in the link https://camo.githubusercontent.com/7ef846842becd81f684fb1f9fcb3daf0267d89b2838b9097c0a7284ac24b68dc/68747470733a2f2f692e696d6775722e636f6d2f35466f7765467a2e6a7067

thanks my friend that's solved for now ! and the new issue is that the call command seems to be disabled or something im using something like this ! 

/call +12817600000 6 daniel chase

and nothing happens ! the command is according to the bot suggestion

**Comment by NameNami** [comment]
ok done

**Comment by darkhacknet** [comment]
> ok done

Yeah bro thanks ! Closing ........
